name: finalproject
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1
  email_validator: '^1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/log_minecraft.jpg
    - assets/data.json
    - assets/default_image.png
    - assets/creeper.jpg
    - assets/bee_minecraft.png
    - assets/images/Logo.png
    - assets/images/Log_ForTheKing.png
    - assets/images/minecraft.png
    - assets/images/ForTheKing.jpg
    - assets/gridIsaac.jpg
    - assets/gridHollow.jpg
    - assets/gridOver.jpg
    - assets/gridSekiro.jpg
    - assets/gridCivil.jpeg
    - assets/gridTerraria.jpg
    - assets/gridCeleste.jpg
    - assets/introIsaac.jpg
    - assets/introOver.jpg
    - assets/introSekiro.jpg
    - assets/introCivil.jpg
    - assets/introTerraria.jpg
    - assets/introCeleste.jpg
    - assets/introHollow.png
    - assets/images/github.png